#include "picosd/protocol/codec.hpp"
namespace picosd::protocol { namespace {
int hex_value(char c) { if (c >= '0' && c <= '9') return c - '0'; if (c >= 'A' && c <= 'F') return c - 'A' + 10; if (c >= 'a' && c <= 'f') return c - 'a' + 10; return -1; }
int b64_value(char c) { if (c >= 'A' && c <= 'Z') return c - 'A'; if (c >= 'a' && c <= 'z') return c - 'a' + 26; if (c >= '0' && c <= '9') return c - '0' + 52; if (c == '+') return 62; if (c == '/') return 63; return -1; }
constexpr char kBase64[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
}  // namespace
std::string encode_hex(const std::uint8_t* data, std::size_t size) { std::string out; out.reserve(size * 2); for (std::size_t i=0;i<size;++i) { out += "0123456789ABCDEF"[data[i] >> 4U]; out += "0123456789ABCDEF"[data[i] & 15U]; } return out; }
CodecError decode_hex(std::string_view input, std::uint8_t* output, std::size_t output_size, std::size_t& written) { written=0; if (input.size()%2) return CodecError::InvalidLength; if (input.size()/2>output_size) return CodecError::OutputTooSmall; for(std::size_t i=0;i<input.size();i+=2){int a=hex_value(input[i]),b=hex_value(input[i+1]);if(a<0||b<0)return CodecError::InvalidCharacter;output[written++]=static_cast<std::uint8_t>((a<<4)|b);}return CodecError::None; }
std::string encode_base64(const std::uint8_t* data, std::size_t size) { std::string out; for(std::size_t i=0;i<size;i+=3){const std::size_t n=size-i; const std::uint32_t v=(static_cast<std::uint32_t>(data[i])<<16U)|(n>1?static_cast<std::uint32_t>(data[i+1])<<8U:0U)|(n>2?data[i+2]:0U);out+=kBase64[(v>>18U)&63U];out+=kBase64[(v>>12U)&63U];out+=n>1?kBase64[(v>>6U)&63U]:'=';out+=n>2?kBase64[v&63U]:'=';}return out; }
CodecError decode_base64(std::string_view in, std::uint8_t* out, std::size_t cap, std::size_t& written) { written=0;if(in.size()%4)return CodecError::InvalidLength;for(std::size_t i=0;i<in.size();i+=4){int a=b64_value(in[i]),b=b64_value(in[i+1]),c=in[i+2]=='='?-2:b64_value(in[i+2]),d=in[i+3]=='='?-2:b64_value(in[i+3]);if(a<0||b<0||c==-1||d==-1||(c==-2&&d!=-2)||( (c==-2||d==-2)&&i+4!=in.size()))return CodecError::InvalidCharacter;const std::size_t count=c==-2?1:(d==-2?2:3);if(written+count>cap)return CodecError::OutputTooSmall;const std::uint32_t v=(static_cast<std::uint32_t>(a)<<18U)|(static_cast<std::uint32_t>(b)<<12U)|(c<0?0U:static_cast<std::uint32_t>(c)<<6U)|(d<0?0U:static_cast<std::uint32_t>(d));out[written++]=static_cast<std::uint8_t>(v>>16U);if(count>1)out[written++]=static_cast<std::uint8_t>(v>>8U);if(count>2)out[written++]=static_cast<std::uint8_t>(v);}return CodecError::None; }
}  // namespace picosd::protocol
